//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaRoom.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaRoom.Web.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem trying to check the E-mail..
        /// </summary>
        public static string Error_ExistEmail {
            get {
                return ResourceManager.GetString("Error_ExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem getting some details, try later please..
        /// </summary>
        public static string Error_GetCustomizedList {
            get {
                return ResourceManager.GetString("Error_GetCustomizedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem getting a list of visas, try later please..
        /// </summary>
        public static string Error_GetTypeOfVisasList {
            get {
                return ResourceManager.GetString("Error_GetTypeOfVisasList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not save your details, try again please..
        /// </summary>
        public static string Error_RegisterApplicant {
            get {
                return ResourceManager.GetString("Error_RegisterApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not save your details..
        /// </summary>
        public static string Error_SaveUser {
            get {
                return ResourceManager.GetString("Error_SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem saving yours Preferred Languages..
        /// </summary>
        public static string Error_SaveUserPreferredLanguages {
            get {
                return ResourceManager.GetString("Error_SaveUserPreferredLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem saving yours Preferred visas.
        /// </summary>
        public static string Error_SaveUserPreferredVisas {
            get {
                return ResourceManager.GetString("Error_SaveUserPreferredVisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string lbl_Age {
            get {
                return ResourceManager.GetString("lbl_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents Meetings!.
        /// </summary>
        public static string lbl_AgentsMeetings {
            get {
                return ResourceManager.GetString("lbl_AgentsMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lbl_City {
            get {
                return ResourceManager.GetString("lbl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lbl_Country {
            get {
                return ResourceManager.GetString("lbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Passport.
        /// </summary>
        public static string lbl_CountryPassport {
            get {
                return ResourceManager.GetString("lbl_CountryPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Residence.
        /// </summary>
        public static string lbl_CountryResidence {
            get {
                return ResourceManager.GetString("lbl_CountryResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Visa.
        /// </summary>
        public static string lbl_CurrentVisa {
            get {
                return ResourceManager.GetString("lbl_CurrentVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Graduation.
        /// </summary>
        public static string lbl_DateofGraduation {
            get {
                return ResourceManager.GetString("lbl_DateofGraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string lbl_Education {
            get {
                return ResourceManager.GetString("lbl_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Test.
        /// </summary>
        public static string lbl_EnglishTest {
            get {
                return ResourceManager.GetString("lbl_EnglishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string lbl_EnglishTestScore {
            get {
                return ResourceManager.GetString("lbl_EnglishTestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lbl_FirstName {
            get {
                return ResourceManager.GetString("lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account..
        /// </summary>
        public static string lbl_IfNotAccoun {
            get {
                return ResourceManager.GetString("lbl_IfNotAccoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Experience.
        /// </summary>
        public static string lbl_JobExperience {
            get {
                return ResourceManager.GetString("lbl_JobExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lbl_LastName {
            get {
                return ResourceManager.GetString("lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Form.
        /// </summary>
        public static string lbl_Log_in_Form {
            get {
                return ResourceManager.GetString("lbl_Log_in_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string lbl_LogIn {
            get {
                return ResourceManager.GetString("lbl_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string lbl_MaritalStatus {
            get {
                return ResourceManager.GetString("lbl_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marn Number.
        /// </summary>
        public static string lbl_Marn {
            get {
                return ResourceManager.GetString("lbl_Marn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Chat!.
        /// </summary>
        public static string lbl_MyChat {
            get {
                return ResourceManager.GetString("lbl_MyChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Questions!.
        /// </summary>
        public static string lbl_MyQuestions {
            get {
                return ResourceManager.GetString("lbl_MyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment!.
        /// </summary>
        public static string lbl_Payment {
            get {
                return ResourceManager.GetString("lbl_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Photo.
        /// </summary>
        public static string lbl_PhotoProfile {
            get {
                return ResourceManager.GetString("lbl_PhotoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Languages.
        /// </summary>
        public static string lbl_PreferredLanguages {
            get {
                return ResourceManager.GetString("lbl_PreferredLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string lbl_Qualification {
            get {
                return ResourceManager.GetString("lbl_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string lbl_Register {
            get {
                return ResourceManager.GetString("lbl_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Visas!.
        /// </summary>
        public static string lbl_SearchVisas {
            get {
                return ResourceManager.GetString("lbl_SearchVisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lbl_State {
            get {
                return ResourceManager.GetString("lbl_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lbl_userName {
            get {
                return ResourceManager.GetString("lbl_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string lbl_ViewDetails {
            get {
                return ResourceManager.GetString("lbl_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Answers!.
        /// </summary>
        public static string lbl_VisaAnswers {
            get {
                return ResourceManager.GetString("lbl_VisaAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visas you are interested.
        /// </summary>
        public static string lbl_VisasInterested {
            get {
                return ResourceManager.GetString("lbl_VisasInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Registration.
        /// </summary>
        public static string msn_AgentRegistration {
            get {
                return ResourceManager.GetString("msn_AgentRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Registration.
        /// </summary>
        public static string msn_ApplicantRegistration {
            get {
                return ResourceManager.GetString("msn_ApplicantRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string msn_WrongUser_Pass {
            get {
                return ResourceManager.GetString("msn_WrongUser_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string qtn_Rememberme {
            get {
                return ResourceManager.GetString("qtn_Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is requered.
        /// </summary>
        public static string rqd_Email {
            get {
                return ResourceManager.GetString("rqd_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First name field is required..
        /// </summary>
        public static string rqd_FirstName {
            get {
                return ResourceManager.GetString("rqd_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last name field is required..
        /// </summary>
        public static string rqd_LastName {
            get {
                return ResourceManager.GetString("rqd_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string rqd_Password {
            get {
                return ResourceManager.GetString("rqd_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name field is required..
        /// </summary>
        public static string rqd_User {
            get {
                return ResourceManager.GetString("rqd_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicants.
        /// </summary>
        public static string txt_applicantsLowCase {
            get {
                return ResourceManager.GetString("txt_applicantsLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICANTS.
        /// </summary>
        public static string txt_applicantsUpperCase {
            get {
                return ResourceManager.GetString("txt_applicantsUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Agent.
        /// </summary>
        public static string txt_AsAgent {
            get {
                return ResourceManager.GetString("txt_AsAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Applicant.
        /// </summary>
        public static string txt_AsApplicant {
            get {
                return ResourceManager.GetString("txt_AsApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Save time and costly mistakes. We&apos;ll fine and matchmake you to the Right Migration Agent.&lt;/p&gt;
        ///            &lt;p&gt;Get multiple reliable and personalized visa advice from Australia&apos;s best registered migration agents.&lt;/p&gt;.
        /// </summary>
        public static string txt_BannerContent {
            get {
                return ResourceManager.GetString("txt_BannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Migration Agent.
        /// </summary>
        public static string txt_BannerTittle {
            get {
                return ResourceManager.GetString("txt_BannerTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOG.
        /// </summary>
        public static string txt_BlogUpperCase {
            get {
                return ResourceManager.GetString("txt_BlogUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string txt_ContactUpperCase {
            get {
                return ResourceManager.GetString("txt_ContactUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string txt_ContactUs {
            get {
                return ResourceManager.GetString("txt_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Brisbane&lt;/li&gt;						&lt;li&gt;&lt;a href=&quot;mailto:itsupport@visaroom.com.au&quot;&gt;Send us an e-mail&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string txt_ContactUsDetails {
            get {
                return ResourceManager.GetString("txt_ContactUsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get client appointments..
        /// </summary>
        public static string txt_hiwmaStep10Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You spend money on marketing. Low return of paying customers..
        /// </summary>
        public static string txt_hiwmaStep1Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You waste time talking and chasing wrong customers..
        /// </summary>
        public static string txt_hiwmaStep2Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition. You want customers to choose you!.
        /// </summary>
        public static string txt_hiwmaStep3Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enter visaRoom..
        /// </summary>
        public static string txt_hiwmaStep4Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy sign up!.
        /// </summary>
        public static string txt_hiwmaStep5Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about yourself. Really simple stuff!.
        /// </summary>
        public static string txt_hiwmaStep6Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out their profile and CV for eligibility answer. Chat..
        /// </summary>
        public static string txt_hiwmaStep7Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisaRoom ONLY matches you with the right leads..
        /// </summary>
        public static string txt_hiwmaStep8Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa applicants will ask questions..
        /// </summary>
        public static string txt_hiwmaStep9Description {
            get {
                return ResourceManager.GetString("txt_hiwmaStep9Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have got Australian visa question..
        /// </summary>
        public static string txt_hiwStep1Description {
            get {
                return ResourceManager.GetString("txt_hiwStep1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want accurate advice only from the best..
        /// </summary>
        public static string txt_hiwStep2Description {
            get {
                return ResourceManager.GetString("txt_hiwStep2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enter VisaRoom..
        /// </summary>
        public static string txt_hiwStep3Description {
            get {
                return ResourceManager.GetString("txt_hiwStep3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about yourself. Really simple stuff!.
        /// </summary>
        public static string txt_hiwStep4Description {
            get {
                return ResourceManager.GetString("txt_hiwStep4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go ahead! Ask you first question!.
        /// </summary>
        public static string txt_hiwStep5Description {
            get {
                return ResourceManager.GetString("txt_hiwStep5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisaRoom matches you with suitable migration agents..
        /// </summary>
        public static string txt_hiwStep6Description {
            get {
                return ResourceManager.GetString("txt_hiwStep6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive multiple visa advice. Chat with them. Check out ther profile..
        /// </summary>
        public static string txt_hiwStep7Description {
            get {
                return ResourceManager.GetString("txt_hiwStep7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one migration agent. Receive proposal. Hire through VisaRoom.
        /// </summary>
        public static string txt_hiwStep8Description {
            get {
                return ResourceManager.GetString("txt_hiwStep8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What You&apos;ll get by joing us?.
        /// </summary>
        public static string txt_hiwWhatYouWin {
            get {
                return ResourceManager.GetString("txt_hiwWhatYouWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Membership.
        /// </summary>
        public static string txt_hiwWhatYouWin1 {
            get {
                return ResourceManager.GetString("txt_hiwWhatYouWin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Australian visa advice anytime-free!.
        /// </summary>
        public static string txt_hiwWhatYouWin2 {
            get {
                return ResourceManager.GetString("txt_hiwWhatYouWin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Customer Support.
        /// </summary>
        public static string txt_hiwWhatYouWin3 {
            get {
                return ResourceManager.GetString("txt_hiwWhatYouWin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Australian&apos;s Best Migration Agents.
        /// </summary>
        public static string txt_hiwWhatYouWin4 {
            get {
                return ResourceManager.GetString("txt_hiwWhatYouWin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upto $1.000 Refund Policy.
        /// </summary>
        public static string txt_hiwWhatYouWin5 {
            get {
                return ResourceManager.GetString("txt_hiwWhatYouWin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string txt_homeUpperCase {
            get {
                return ResourceManager.GetString("txt_homeUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW IT WORKS.
        /// </summary>
        public static string txt_HowItWorks {
            get {
                return ResourceManager.GetString("txt_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us now!.
        /// </summary>
        public static string txt_joinUsNow {
            get {
                return ResourceManager.GetString("txt_joinUsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string txt_LoginUpperCase {
            get {
                return ResourceManager.GetString("txt_LoginUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Agents.
        /// </summary>
        public static string txt_MigrationAgentLowCase {
            get {
                return ResourceManager.GetString("txt_MigrationAgentLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIGRATION AGENTS.
        /// </summary>
        public static string txt_MigrationAgentUpperCase {
            get {
                return ResourceManager.GetString("txt_MigrationAgentUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string txt_Navigation {
            get {
                return ResourceManager.GetString("txt_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ready to get Australian visa answers?&lt;/p&gt;
        ///               &lt;p&gt;&lt;b&gt;It is Free!&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        public static string txt_ReadyGetAnswers {
            get {
                return ResourceManager.GetString("txt_ReadyGetAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string txt_RegisterLowerCase {
            get {
                return ResourceManager.GetString("txt_RegisterLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string txt_RegisterUpperCase {
            get {
                return ResourceManager.GetString("txt_RegisterUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Submit to our news letter&lt;/h5&gt;
        ///					&lt;p&gt;Submit and get all the info about our 
        ///						work and new blog inputs.&lt;/p&gt;.
        /// </summary>
        public static string txt_SubmitNewLetterDescription {
            get {
                return ResourceManager.GetString("txt_SubmitNewLetterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt; Greater Information&lt;/b&gt; 
        ///                            &lt;br /&gt;
        ///                            Access, view and learn  migration agents profile.
        ///                            Make informed decision..
        /// </summary>
        public static string txt_whyVisaRoomStep1 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Easy Matchmaking&lt;/b&gt; 
        ///                            &lt;br /&gt;
        ///                            Connecting migration agents that matches your profile means you save time..
        /// </summary>
        public static string txt_whyVisaRoomStep2 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Personlized Advice&lt;/b&gt; 
        ///                            &lt;br /&gt;
        ///                            1-2-1 chat and profile view allows  you to get exclusive services..
        /// </summary>
        public static string txt_whyVisaRoomStep3 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Wider Advice&lt;/b&gt; 
        ///                                &lt;br /&gt;
        ///                                Collection of Australia&apos;s best migration agents across various visa expertise under one spot..
        /// </summary>
        public static string txt_whyVisaRoomStep4 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Avoid Costly Mistakes&lt;/b&gt; 
        ///                                &lt;br /&gt;
        ///                                Get advice from registered and carefully selected migration agents not forums or unqualified source..
        /// </summary>
        public static string txt_whyVisaRoomStep5 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Our Guarantee&lt;/b&gt; 
        ///                        &lt;br /&gt;
        ///                        If you are not 100% satisfed with the service provided by migration agent you find on VisaRoom, you&apos;ll receive up to $1.000 of your money back!
        ///                        &lt;br /&gt;
        ///                        &lt;p style=&quot;text-align:center &quot;&gt;&lt;b&gt;Less Risk!&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        public static string txt_whyVisaRoomStep6 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will love VisaRoom.
        /// </summary>
        public static string txt_whyVisaRoomTitle1 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A safer, simpler and easier way.
        /// </summary>
        public static string txt_whyVisaRoomTitle2 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to choose migration agents.
        /// </summary>
        public static string txt_whyVisaRoomTitle3 {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY VISAROOM.
        /// </summary>
        public static string txt_whyVisaRoomUpperCase {
            get {
                return ResourceManager.GetString("txt_whyVisaRoomUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not valid.
        /// </summary>
        public static string typ_Email {
            get {
                return ResourceManager.GetString("typ_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email {0} already Exist!.
        /// </summary>
        public static string val_UserEmailExists {
            get {
                return ResourceManager.GetString("val_UserEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th user name is already taken. Try another one..
        /// </summary>
        public static string val_UserExists {
            get {
                return ResourceManager.GetString("val_UserExists", resourceCulture);
            }
        }
    }
}
